export const FETCH_CART_ITEMS_START = 'FETCH_CART_ITEMS_START';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS';
export const FETCH_CART_ITEMS_FAILURE = 'FETCH_CART_ITEMS_FAILURE';

export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS';

export const INCREASE_CART_ITEM_QUANTITY_SUCCESS =
  'INCREASE_CART_ITEM_QUANTITY_SUCCESS';
export const INCREASE_CART_ITEM_QUANTITY_FAILURE =
  'INCREASE_CART_ITEM_QUANTITY_FAILURE';

export const DECREASE_CART_ITEM_QUANTITY_SUCCESS =
  'DECREASE_CART_ITEM_QUANTITY_SUCCESS';
export const DECREASE_CART_ITEM_QUANTITY_FAILURE =
  'DECREASE_CART_ITEM_QUANTITY_FAILURE';

export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
